services:
  laminas:
    build:
      args:
        user: danilocolasso
        uid: 1000
      context: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager
      MYSQL_USER: danilocolasso
      MYSQL_PASSWORD: strongpassword
    user: "1000:1000"
    ports:
      - "3306:3306"
    volumes:
      - ./data/database/data:/var/lib/mysql
      - ./data/database/dump/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge