<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

$title = 'Delete task';
$url   = $this->url('task', ['action' => 'delete', 'id' => $id]);
?>
<h1 class="text-2xl font-medium text-center md:text-start">
    <?= $this->escapeHtml($title) ?>
</h1>

<div class="flex flex-col gap-4">
    <div class="text-center md:text-start">
        Are you sure that you want to delete
        <span class="font-medium">"<?= $this->escapeHtml($task->title) ?>"</span>
        ?
    </div>

    <form action="<?= $url ?>" method="post">
        <div class="flex flex-col-reverse md:flex-row md:flex-row gap-2">
            <input type="hidden" name="id" value="<?= (int) $task->id ?>" />
            <input
                    type="submit"
                    class="text-center rounded-md px-4 py-2 text-md bg-gray-200 border border-transparent hover:border-gray-400 cursor-pointer"
                    name="del"
                    value="No"
            />
            <input
                type="submit"
                class="text-white text-center rounded-md px-4 py-2 text-md bg-blue-500 hover:bg-blue-500/80 border border-transparent hover:border-blue-800 cursor-pointer"
                name="del"
                value="Yes"
            />
        </div>
    </form>
</div>