<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

$title = 'Edit task';
$this->headTitle($title);
?>
<h1 class="text-2xl font-medium text-center md:text-start">
    <?= $this->escapeHtml($title) ?>
</h1>

<div class="flex flex-col gap-4">
    <?php
    $fieldClasses = 'rounded-sm font-normal';
    $labelClasses = 'flex flex-col gap-1 font-medium';

    /** @var Laminas\Form\Form $form */
    $form
        ->setAttribute('class', 'flex flex-col gap-2')
        ->setAttribute('action', $this->url('task', ['action' => 'add']));

    $form->get('title')
        ->setAttribute('class', $fieldClasses)
        ->setAttribute('placeholder', 'Task title')
        ->setOptions(['label_attributes' => ['class' => $labelClasses]]);

    $form->get('description')
        ->setAttribute('class', $fieldClasses)
        ->setAttribute('placeholder', 'Task description')
        ->setOptions(['label_attributes' => ['class' => $labelClasses]]);

    $form->get('status')
        ->setAttribute('class', $fieldClasses)
        ->setAttribute('placeholder', 'Task description')
        ->setOptions(['label_attributes' => ['class' => 'flex flex-row-reverse items-center justify-end gap-2 font-medium']]);

    $form->get('submit')
        ->setAttribute(
            'class',
            'text-white rounded-md bg-blue-500 hover:bg-blue-500/80 px-4
                py-2 border border-transparent hover:border-blue-800 text-center cursor-pointer'
        );

    $form->setAttribute('action', $this->url('task', [
        'action' => 'edit',
        'id' => $id,
    ]));

    $form->prepare();

    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formRow($form->get('title'));
    echo $this->formRow($form->get('description'));
    echo $this->formRow($form->get('status'));
    ?>

    <div class="flex flex-col-reverse md:flex-row md:flex-row md:justify-end gap-2">
        <a
                class="text-center rounded-md px-4 py-2 text-md bg-gray-200 border border-transparent hover:border-gray-400 cursor-pointer"
                href="<?= $this->url('task', ['action' => 'index']) ?>"
        >
            Cancel
        </a>
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </div>

    <?php echo $this->form()->closeTag(); ?>
</div>

