<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

$title = 'View task';
$this->headTitle($title);
?>
<h1 class="text-2xl font-medium text-center md:text-start">
    <?= $this->escapeHtml($title) ?>
</h1>

<div class="flex flex-col gap-2">
    <div class="flex gap-1">
        <span class="font-medium">Title:</span>
        <span><?= $this->escapeHtml($task->title) ?></span>
    </div>
    <div class="flex gap-1">
        <span class="font-medium">Description:</span>
        <span><?= $this->escapeHtml($task->description) ?></span>
    </div>
    <div class="flex gap-1">
        <span class="font-medium">Status:</span>
        <span class="capitalize"><?= $this->escapeHtml($task->status->value) ?></span>
    </div>
    <div class="flex gap-1">
        <span class="font-medium">Created at:</span>
        <span><?= $this->escapeHtml($task->createdAt->format('Y-m-d H:i:s')) ?></span>
    </div>
    <div class="flex gap-1">
        <span class="font-medium">Updated at:</span>
        <span><?= $this->escapeHtml($task->updatedAt->format('Y-m-d H:i:s')) ?></span>
    </div>
    <a
        class="text-center rounded-md px-4 py-2 text-md bg-gray-200 border border-transparent hover:border-gray-400 cursor-pointer md:self-start"
        href="<?= $this->url('task', ['action' => 'index']) ?>"
    >
        Back
    </a>
</div>