<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en" class="w-full h-full">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Task Manager')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                'rel' => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath() . '/img/favicon.ico'
            ])
        ?>

        <?= $this->inlineScript()
            ->prependFile('https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp') ?>
        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body class="w-full min-h-full text-gray-800">
        <nav class="flex justify-center md:justify-start bg-blue-500 px-8 py-4" role="navigation">
            <a class="flex flex-col md:flex-row items-center gap-2 md:gap-4" href="<?= $this->url('home') ?>">
                <img class="h-16" src="<?= $this->basePath('img/laminas-logo.svg') ?>" alt="Laminas">
                <span class="text-white text-sm">Task Manager</span>
            </a>
        </nav>
        <div class="flex flex-col justify-between bg-gray-100 min-h-[calc(100vh-7.75rem)]">
            <div class="flex flex-col gap-8 flex-grow bg-white border-gray-100 rounded-md shadow-sm p-4 m-4">
                <?= $this->content ?>
            </div>
            <footer class="flex items-center justify-center md:justify-end p-4 gap-1">
                <span class="cursor-default">Made with ♡ by</span>
                <a class="text-blue-500 hover:text-blue-800" href="https://www.linkedin.com/in/danilocolasso/">Danilo Colasso</a>
            </footer>
        </div>
    </body>
</html>
